# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - awad-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registry0104.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_60a6212d4d3146e69a32b27c7f620e1e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6d2b23c9b6124fbdb42826040ee12246 }}

    - name: 'Create env file'
      working-directory: /usr/src/app
      run: |
        touch .env
        echo MONGODB_CONNECTION_STRING=${{secrets.MONGODB_CONNECTION_STRING}} >> .env
        echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
        echo API_PORT=${{secrets.API_PORT}} >> .env
        echo API_KEY=${{secrets.API_KEY}} >> .env
        echo GEMENI_API_KEY=${{secrets.GEMENI_API_KEY}} >> .env
        cat .env

    - name: 'Create firebase admin config'
      working-directory: /usr/src/app
      run: |
        touch firebase-config.json
        echo ${{secrets.FIREBASE_ADMIN_CONFIG}} | base64 --decode | jq >> firebase-config.json
        cat firebase-config.json

    - name: 'List'
      working-directory: /github/workspace
      run: ls

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry0104.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_60a6212d4d3146e69a32b27c7f620e1e }}/registry0104/awad-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'awad-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2dc2c45e14bd43df9c92e7064c905672 }}
        images: 'registry0104.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_60a6212d4d3146e69a32b27c7f620e1e }}/registry0104/awad-backend:${{ github.sha }}'
